netguru-code-college/vol2-delta

- app/controllers/static_pages_controller.rb
It's adding a static pages controller with methods: index, about, rules, contact.
My branch name is wrong, I'm not creating a model, my bad.
I'm creating this branch because I'm sharing work with Karolina.
> Add static pages controller

- app/views/static_pages/contact.haml
- app/views/static_pages/index.haml
- config/routes.rb
It adds index page as a homepage and contact page.
> Add index and contact pages

- app/views/static_pages/about.html.haml
- app/views/static_pages/rules.html.haml
- config/routes.rb
added static pages: about and rules of ranking
> add static pages about and rules

- app/models/ascent.rb
- app/models/crag.rb
- app/models/route.rb
- app/models/sector.rb
- config/routes.rb
- db/migrate/20180223105049_add_crag_id_to_sector.rb
- db/migrate/20180223105212_add_sector_id_to_route.rb
- db/migrate/20180223105511_add_route_id_to_ascent.rb
- db/migrate/20180223105745_add_user_id_to_ascent.rb
- db/schema.rb
> Improve asociations for models and nested routes for this models

- app/models/ascent.rb
- app/models/climbing_route.rb
- app/models/sector.rb
- config/routes.rb
- db/migrate/20180223135608_rename_routes_to_climbing_routes.rb
- db/schema.rb
I've renamed Routes table to Climbing routes (including dependencies and all files using old name)
> Rename routes to climbing_routes

- app/controllers/ascent_controller.rb
- app/models/ascent.rb
- app/models/ascent_style.rb
- app/models/route_grade.rb
- app/services/climbing_routes_services.rb
- db/migrate/20180223135320_create_ascent_styles.rb
- db/migrate/20180223135654_create_route_grades.rb
- db/migrate/20180223141450_fix_column_name.rb
- db/schema.rb
- db/seeds.rb
seeds database with points depending on grades and ascet style
> Grades and styles model

- app/controllers/crags_controller.rb
- app/decorators/crag_decorator.rb
- app/helpers/crags_helper.rb
- app/views/crags/_crag.json.jbuilder
- app/views/crags/_form.html.haml
- app/views/crags/edit.html.haml
- app/views/crags/index.html.haml
- app/views/crags/index.json.jbuilder
- app/views/crags/new.html.haml
- app/views/crags/show.html.haml
- app/views/crags/show.json.jbuilder
- app/views/shared/_gmap.html.haml
- app/views/shared/_navbar.html.haml
- config/routes.rb
- db/migrate/20180225074853_change_column_names.rb
- db/schema.rb
Lots of new stuff: crags, google maps, etc.
> Google maps

- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/views/crags/show.html.haml
- app/views/layouts/application.html.haml
- app/views/shared/_gmap.html.haml
- app/views/shared/_navbar.html.haml
- db/schema.rb
> General ui

- app/models/ascent.rb
- db/migrate/20180226135232_add_route_grade_id_to_climbing_route.rb
- db/schema.rb
new column in climbing_routes with grade_id
> add route grade id to climbing route

- app/models/climbing_route.rb
- app/models/route_grade.rb
- db/migrate/20180226142749_delete_grade_from_climbing_routes.rb
- db/schema.rb
- db/seeds.rb
remove column grade from climbing routes
add relation one - many  between climbing route and grade
> Create relation between climbing routes and grades

- db/seeds.rb
removed grade column from climbing_routes
> Points from grades and styles

- README.md
> ReadMe version 1

- app/assets/javascripts/ranking.coffee
- app/assets/stylesheets/ranking.scss
- app/controllers/ranking_controller.rb
- app/decorators/ranking_decorator.rb
- app/helpers/ranking_helper.rb
- app/views/ranking/index.html.haml
- app/views/shared/_navbar.html.haml
- app/views/static_pages/rules.html.haml
- config/routes.rb
- db/schema.rb
> Rank controller

- app/models/ascent.rb
- app/models/ascent_style.rb
- db/migrate/20180226154523_add_ascent_style_id_to_ascent.rb
- db/migrate/20180226154803_remove_style_from_ascent.rb
add reference between styles and ascents
added relation one - many between ascent ans styles
remove column styles from ascent
> Add reference to styles from ascents

- db/schema.rb
Resolve differences witch schema
> Resolve differences witch schema

- db/schema.rb
- db/seeds.rb
> Add 10 ascents to seed

- db/migrate/20180227083918_delete_grade_from_ascent.rb
- db/schema.rb
Delete column grade from ascent
> Delete column grade from ascent

- db/seeds.rb
> Modify ranges of rand in id's

- app/models/route_grade.rb
- db/migrate/20180227093535_change_climbing_routes_id_to_climbing_route_id_in_ascents.rb
- db/schema.rb
- db/seeds.rb
repair invalid rand id's
rename colimn in ascents from climbing_routes_id to climbing _route_id
> Repair seeds

- app/models/ascent.rb
- app/models/climbing_route.rb
- app/models/route_grade.rb
- app/services/climbing_routes_services.rb
- db/seeds.rb
- change seeds
- change associations between models
- create method for counting ascent points
> Create method for counting points for ascent

- app/models/ascent.rb
- app/models/route_grade.rb
- add validation to ascent
- remove redundant comments and blanks
> Counting points

- app/controllers/ranking_controller.rb
- app/models/user.rb
- app/views/ranking/index.html.haml
> Add users to ranking page

- Gemfile
- Gemfile.lock
- app/controllers/climbing_routes_controller.rb
- app/views/climbing_routes/show_all_climbing_routes.html.haml
- app/views/kaminari/_first_page.html.haml
- app/views/kaminari/_gap.html.haml
- app/views/kaminari/_last_page.html.haml
- app/views/kaminari/_next_page.html.haml
- app/views/kaminari/_page.html.haml
- app/views/kaminari/_paginator.html.haml
- app/views/kaminari/_prev_page.html.haml
> Kaminari pagination

- app/controllers/ascents_controller.rb
- app/controllers/climbing_routes_controller.rb
- app/controllers/crags_controller.rb
- app/controllers/sectors_controller.rb
> basic user authentication

- app/views/devise/registrations/new.html.haml
- app/views/devise/sessions/new.html.haml
minor improvements in login and register forms.
> Login register view

- config/environments/production.rb
> Change prod env settings

- app/controllers/crags_controller.rb
- app/views/crags/index.html.haml
- app/views/crags/show.html.haml
- app/views/devise/sessions/new.html.haml
> Create crag map

- app/models/ability.rb
- app/models/ascent.rb
- app/models/ascent_style.rb
- app/models/climbing_route.rb
- app/models/crag.rb
- app/models/route_grade.rb
- app/models/sector.rb
- app/models/user.rb
#Added validations for models:
* user
* sectors
* route_grade
* crag
* climbing_route
* ascent_style
- cancancan's ability model
> Validations

- app/assets/stylesheets/application.scss
- app/controllers/crags_controller.rb
- app/controllers/static_pages_controller.rb
- app/views/crags/index.html.haml
- app/views/crags/show.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/static_pages/index.haml
Last ascents feature on home page
> Last ascents

- app/controllers/ascents_controller.rb
- app/views/ascents/edit.html.haml
- app/views/ascents/index.html.haml
- app/views/ascents/new.html.haml
- app/views/user_profile/show.html.haml
-Add links Edit and Destroy to Ascent in User profile
-Add link Back in Edit Ascent View
> Links in ascents

- app/controllers/crags_controller.rb
- app/models/crag.rb
- app/views/crags/new.html.haml
- app/views/ranking/index.html.haml
> fixes country issue in ugly way

- app/controllers/ascents_controller.rb
- app/views/ascents/show.html.haml
> show view for ascent

- app/assets/stylesheets/application.scss
- app/views/ranking/index.html.haml
- app/views/static_pages/rules.html.haml
> changes table position/width

- app/views/ascents/_errors.html.haml
- app/views/crags/index.html.haml
- app/views/crags/new.html.haml
- app/views/crags/show.html.haml
- app/views/layouts/application.html.haml
- app/views/shared/_messages.html.haml
This task will extract flash messages from all views to partial which is rendered in application layout.
> Extract flash messages from views to app layout partial

- app/helpers/user_profile_helper.rb
- app/views/climbing_routes/show.html.haml
- app/views/sectors/show.html.haml
-Refactor view in sector#show
-Add buttons: "Add", "Edit", "Delete"
> Repair users names

- app/views/climbing_routes/index.html.haml
This PR will add jumbotron to climbing routes index page.
> Add jumbotron to climbing routes index page

- app/helpers/user_profile_helper.rb
- app/models/ascent_style.rb
- db/seeds.rb
> Fix validation
